Added automatic installation of rustdesk in target when required

diff --git a/lliurex-rdesk b/lliurex-rdesk
--- a/lliurex-rdesk
+++ b/lliurex-rdesk
@@ -8,6 +8,12 @@ main(){
 	case "$ACTION" in
 		enable)
 			root_test || die "You must be root to run this program"
+			if ! test_rustdesk_installation ; then
+				if ! install_rustdesk ; then
+					die "Rustkdesk installation failed. Exitting"
+				fi
+			fi
+
 			CONN_PASS="$(gen_password)"
 			enable_connection "$CONN_PASS"
 			echo "USE PASSWORD: $CONN_PASS"
@@ -83,6 +89,28 @@ root_test(){
 	return 0
 }
 
+test_rustdesk_installation(){
+	PKG_NAME="rustdesk"
+	dpkg -l "$PKG_NAME" >/dev/null 2>/dev/null || return 1
+	return 0
+}
+
+install_rustdesk(){
+	RUSTDESK_URL="https://github.com/rustdesk/rustdesk/releases/download/1.4.6/rustdesk-1.4.6-x86_64.deb"
+	TMP_DIR="$(mktemp -d)"
+	DEST_FILE="$TMP_DIR/rustdesk.deb"
+	wget -O "$DEST_FILE" "$RUSTDESK_URL"
+	rc=1
+	echo "$DEST_FILE"
+	ls -al "$DEST_FILE"
+
+	if [ -s "$DEST_FILE" ] ; then
+              rc=0
+	      apt install -y "$DEST_FILE" || rc=$?
+	fi
+	rm -fr "$TMP_DIR"
+	return $rc
+}
 
 gen_password(){
 	tr -dc A-Za-z0-9 </dev/urandom | head -c 8
